name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'yarn'
      
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      
      - name: Run tests
        run: yarn test
      
      - name: Run linting
        run: yarn lint
      
      - name: Build Nuxt module
        run: yarn nuxt-module-build build
      
      - name: Verify build output
        run: |
          echo "=== Checking dist folder ==="
          ls -la dist/
          echo "=== Verifying required files exist ==="
          test -f dist/module.cjs && echo "✅ module.cjs exists" || echo "❌ module.cjs missing"
          test -f dist/module.mjs && echo "✅ module.mjs exists" || echo "❌ module.mjs missing" 
          test -f dist/types.d.ts && echo "✅ types.d.ts exists" || echo "❌ types.d.ts missing"
      
      - name: Create package tarball
        run: |
          yarn pack
          # Find the generated tarball (yarn pack creates different filename format)
          TARBALL=$(ls *.tgz)
          echo "Created package: $TARBALL"
          
          # Rename to include version
          VERSION=${GITHUB_REF#refs/tags/}
          mv "$TARBALL" "nuxt-lottie-${VERSION}.tgz"
          echo "Renamed to: nuxt-lottie-${VERSION}.tgz"
      
      - name: Create Release
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          gh release create "${VERSION}" "nuxt-lottie-${VERSION}.tgz" \
            --title "Release ${VERSION}" \
            --notes "## 🚀 Installation

          \`\`\`bash
          bun add https://github.com/${{ github.repository }}/releases/download/${VERSION}/nuxt-lottie-${VERSION}.tgz
          \`\`\`

          ## 📦 What's included
          - Built Nuxt module with TypeScript support
          - ESM and CJS exports
          - Type definitions included
          - Ready for Nuxt 3/4 projects

          ## ✅ Verified build output
          - \`dist/module.cjs\` - CommonJS module
          - \`dist/module.mjs\` - ES module  
          - \`dist/types.d.ts\` - TypeScript definitions"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}